// actionTypes.js
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const UPDATE_OUTPOST_NAME = 'UPDATE_OUTPOST_NAME';
export const ADD_OUTPOST = 'ADD_OUTPOST';
export const REMOVE_OUTPOST = 'REMOVE_OUTPOST';
export const TOGGLE_LINKING_RESOURCES = 'TOGGLE_LINKING_RESOURCES';
export const TOGGLE_CONSIDER_LINKING_RESOURCES = 'TOGGLE_CONSIDER_LINKING_RESOURCES';
export const GET_OUTPOST_RESOURCES = 'GET_OUTPOST_RESOURCES';
export const GET_OUTPOST_NAME = 'GET_OUTPOST_NAME';
export const SET_RESULTS = 'SET_RESULTS';
export const UPDATE_BEST_COMBO = 'UPDATE_BEST_COMBO';
export const FIND_BEST_OUTPOST_COMBINATION = 'FIND_BEST_OUTPOST_COMBINATION';
export const FIND_BEST_COMBO_FOR_BASE = 'FIND_BEST_COMBO_FOR_BASE';
export const FIND_BEST_LINKED_COMBO = 'FIND_BEST_LINKED_COMBO';
export const CAN_PRODUCE_GOOD = 'CAN_PRODUCE_GOOD';
export const GET_PRODUCABLE_GOODS = 'GET_PRODUCABLE_GOODS';
export const GET_UNUSED_RESOURCES = 'GET_UNUSED_RESOURCES';