// actionTypes.js
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const UPDATE_OUTPOST_NAME = 'UPDATE_OUTPOST_NAME';
export const ADD_OUTPOST = 'ADD_OUTPOST';
export const REMOVE_OUTPOST = 'REMOVE_OUTPOST';
export const TOGGLE_LINKING_RESOURCES = 'TOGGLE_LINKING_RESOURCES';
